language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby
  - jruby
  - rbx-2
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
